version: "3.8"
services:
    py:
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      image: working_with_db_prod
      container_name: working_with_DB_prod
      build:
        ./py
      environment:
        - DATABASE=postgres
        - SQL_PORT=5432
        - SQL_HOST=localhost
        - MODE=prod
      depends_on:
        - db
      network_mode: host
      volumes:
        - ./py:/usr/src/app/
        - ./py/logger:/logger
    db:
      container_name: postgres
      image: postgres:13.3
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=egor
        - POSTGRES_PASSWORD=krasnov
        - POSTGRES_DB=dockerHW_db
      volumes:
        - ./dockerDB:/var/lib/postgresql/data

#volumes:
#  postgres_data: